#!/bin/bash

# SSmart POS Flutter Admin App - Quick Start Script
# Interactive setup with optional credential input

set -e  # Exit on error

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Helper functions
print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_info() {
    echo -e "${BLUE}ℹ${NC} $1"
}

print_header() {
    echo ""
    echo -e "${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${CYAN}${BOLD}$1${NC}"
    echo -e "${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo ""
}

# Get script directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$SCRIPT_DIR"

clear

print_header "🚀 SSmart POS Flutter Admin - Quick Start"

echo -e "${BOLD}Welcome!${NC} This interactive script will help you get started in under 5 minutes."
echo ""

# Step 1: Run basic setup
print_header "Step 1: Running Basic Setup"

if [ -f "./setup.sh" ]; then
    chmod +x ./setup.sh
    if ./setup.sh; then
        print_success "Basic setup completed"
    else
        print_error "Setup failed"
        exit 1
    fi
else
    print_error "setup.sh not found!"
    exit 1
fi

# Step 2: Interactive Firebase configuration
print_header "Step 2: Firebase Configuration"

echo -e "${BOLD}Configuration Options:${NC}"
echo ""
echo "1. ${CYAN}.env file${NC} (Local Development)"
echo "   • For running app locally"
echo "   • Faster, simpler"
echo "   • This script sets this up"
echo ""
echo "2. ${CYAN}GitHub Secrets${NC} (CI/CD)"
echo "   • For GitHub Actions automated builds"
echo "   • More secure, encrypted"
echo "   • See GITHUB_SECRETS_SETUP.md"
echo ""
echo "This script will configure .env for LOCAL development."
echo ""

if [ -f ".env" ]; then
    # Check if .env has placeholder values
    if grep -q "your_api_key_here" .env 2>/dev/null; then
        echo -e "${BOLD}Your .env file needs Firebase credentials.${NC}"
        echo ""
        echo "You have two options:"
        echo "  1. Enter credentials now (interactive)"
        echo "  2. Edit .env file manually later"
        echo ""
        read -p "Would you like to enter Firebase credentials now? (y/N): " -n 1 -r
        echo

        if [[ $REPLY =~ ^[Yy]$ ]]; then
            echo ""
            print_info "Great! Let's configure Firebase."
            echo ""
            echo -e "${YELLOW}Tip:${NC} Get these values from:"
            echo "     https://console.firebase.google.com → Project Settings → General"
            echo ""

            # Read Firebase credentials
            read -p "Firebase API Key: " FIREBASE_API_KEY
            read -p "Firebase Auth Domain (e.g., yourproject.firebaseapp.com): " FIREBASE_AUTH_DOMAIN
            read -p "Firebase Database URL (e.g., https://yourproject-default-rtdb.firebaseio.com): " FIREBASE_DATABASE_URL
            read -p "Firebase Project ID: " FIREBASE_PROJECT_ID
            read -p "Firebase Storage Bucket (e.g., yourproject.appspot.com): " FIREBASE_STORAGE_BUCKET
            read -p "Firebase Messaging Sender ID: " FIREBASE_MESSAGING_SENDER_ID
            read -p "Firebase App ID: " FIREBASE_APP_ID
            read -p "Firebase Measurement ID (e.g., G-XXXXXXXXXX): " FIREBASE_MEASUREMENT_ID

            # Write to .env file
            cat > .env << EOF
# Firebase Configuration
# Generated by quickstart.sh on $(date)

FIREBASE_API_KEY=$FIREBASE_API_KEY
FIREBASE_AUTH_DOMAIN=$FIREBASE_AUTH_DOMAIN
FIREBASE_DATABASE_URL=$FIREBASE_DATABASE_URL
FIREBASE_PROJECT_ID=$FIREBASE_PROJECT_ID
FIREBASE_STORAGE_BUCKET=$FIREBASE_STORAGE_BUCKET
FIREBASE_MESSAGING_SENDER_ID=$FIREBASE_MESSAGING_SENDER_ID
FIREBASE_APP_ID=$FIREBASE_APP_ID
FIREBASE_MEASUREMENT_ID=$FIREBASE_MEASUREMENT_ID
EOF

            print_success "Firebase credentials saved to .env"
        else
            print_info "No problem! You can edit .env file manually later."
            echo ""
            echo "Run this command when ready:"
            echo -e "  ${YELLOW}nano .env${NC}  or  ${YELLOW}open .env${NC}"
        fi
    else
        print_success ".env file appears to be configured!"
    fi
else
    print_error ".env file not found after setup!"
    exit 1
fi

# Step 3: Validate Firebase configuration
print_header "Step 3: Validating Configuration"

if [ -f "scripts/validate_firebase.dart" ]; then
    print_info "Running Firebase configuration validator..."
    echo ""

    if dart run scripts/validate_firebase.dart; then
        echo ""
        print_success "Configuration validation passed!"
    else
        echo ""
        print_warning "Configuration validation had issues."
        print_info "You may need to edit .env file and fix the issues."
    fi
else
    print_warning "Validator script not found. Skipping validation."
fi

# Step 4: Ask if user wants to run the app
print_header "Step 4: Launch App"

echo -e "${BOLD}Setup is complete!${NC}"
echo ""

if grep -q "your_api_key_here" .env 2>/dev/null; then
    print_warning "Remember to configure your .env file before running the app!"
    echo ""
    echo "Edit with: ${YELLOW}nano .env${NC}  or  ${YELLOW}open .env${NC}"
    echo ""
    echo "Then run: ${YELLOW}flutter run${NC}"
else
    read -p "Would you like to run the app now? (y/N): " -n 1 -r
    echo

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        echo ""
        print_info "Launching app..."
        echo ""
        flutter run
    else
        echo ""
        print_info "You can run the app anytime with:"
        echo -e "  ${YELLOW}flutter run${NC}"
    fi
fi

# Final information
print_header "📚 Resources"

echo "Documentation:"
echo "  • Quick Reference: ${CYAN}README.md${NC}"
echo "  • Local Setup (.env): ${CYAN}ENV_SETUP.md${NC}"
echo "  • CI/CD Setup (GitHub Secrets): ${CYAN}GITHUB_SECRETS_SETUP.md${NC}"
echo "  • iOS Build Guide: ${CYAN}IOS_BUILD_SETUP.md${NC}"
echo ""

echo "Common Commands:"
echo "  • Run app: ${YELLOW}flutter run${NC}"
echo "  • Build for simulator: ${YELLOW}flutter build ios --simulator${NC}"
echo "  • Validate config: ${YELLOW}dart run scripts/validate_firebase.dart${NC}"
echo "  • Check Flutter: ${YELLOW}flutter doctor${NC}"
echo ""

echo "Next Steps:"
echo "  • ${CYAN}Local dev:${NC} You're all set! Just run the app."
echo "  • ${CYAN}CI/CD:${NC} Set up GitHub Secrets (see GITHUB_SECRETS_SETUP.md)"
echo ""

print_success "Happy coding! 🎉"
echo ""
